import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopAPI, DesktopEvent } from '../shared/types';
const methods = new Set([
  'review:chunks',
  'review:chunk',
  'review:comment',
  'review:remove-comment',
  'review:branches',
  'review:branch',
  'review:push-preview',
  'review:push',
  'review:prs',
  'review:pr-preview',
  'review:pr-create',
  'worktrees:list',
  'worktrees:attach',
  'worktrees:handoff',
  'worktrees:preview',
  'worktrees:apply',
  'worktrees:archive',
  'worktrees:restore',
  'actions:list',
  'actions:save',
  'actions:remove',
  'actions:preview',
  'actions:run',
  'actions:cancel',
  'configuration:list',
  'configuration:open',
  'configuration:save',
  'sessions:list',
  'sessions:import',
  'sessions:fork',
  'sessions:points',
  'sessions:preview',
  'sessions:rewind',
  'integration:list',
  'integration:action',
  'state',
  'runtime:info',
  'chats:search',
  'chats:search-cancel',
  'mcp:list',
  'mcp:add',
  'mcp:change',
  'mcp:doctor',
  'project:add',
  'project:edit',
  'thread:new',
  'thread:edit',
  'agent:connect',
  'agent:prompt',
  'agent:cancel',
  'agent:disconnect',
  'agent:config',
  'agent:authenticate',
  'permissions',
  'permission:answer',
  'settings:save',
  'settings:executable',
  'files:list',
  'files:read',
  'files:open',
  'files:save',
  'editor:dirty',
  'attachments:pick',
  'git:state',
  'git:diff',
  'git:update',
  'git:commit',
  'git:worktree',
  'terminal:open',
  'terminal:write',
  'terminal:resize',
  'terminal:close',
  'external:open',
  'workspace:reveal',
]);
const api: DesktopAPI = {
  call: (method, args = {}) => {
    if (!methods.has(method)) return Promise.reject(new Error('Unknown desktop operation.'));
    return ipcRenderer.invoke('desktop:call', method, args);
  },
  onEvent: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, event: DesktopEvent) => callback(event);
    ipcRenderer.on('desktop:event', listener);
    return () => ipcRenderer.removeListener('desktop:event', listener);
  },
};
contextBridge.exposeInMainWorld('desktop', api);
